# PINN config template
data:
  data_dir: "data/processed"
  train_csv: "data/processed/train.csv"
model:
  hidden_layers: [128,128,128]
  activation: "tanh"
training:
  optimizer: "adam"
  lr: 0.001
  epochs: 10000
misc:
  output_dir: "results"
